### ISSUE TITLE
Control Peer proxy registration can cause panic

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#100]
```
fatal error: concurrent map writes

goroutine 5 [running]:
runtime.throw(0x663fc0, 0x15)
	/usr/lib/go/src/runtime/panic.go:530 +0x90 fp=0xc820038bb8 sp=0xc820038ba0
runtime.mapassign1(0x5a9ac0, 0xc8200109f0, 0xc820038cb0, 0xc820038de0)
	/usr/lib/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc820038c60 sp=0xc820038bb8
main.(*Proxy).HandleMessage(0xc820014640, 0xd, 0xc8203cd950, 0x0, 0x0, 0xc8200ac028, 0x1000, 0x1000)
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/p2p-cp/proxy.go:163 +0x6c7 fp=0xc820038ee8 sp=0xc820038c60
main.(*Proxy).HandleMessage-fm(0xd, 0xc8203cd950, 0x0, 0x0, 0xc8200ac028, 0x1000, 0x1000)
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/p2p-cp/proxy.go:53 +0x66 fp=0xc820038f30 sp=0xc820038ee8
github.com/subutai-io/p2p/lib.(*PTPNet).Listen(0xc8200ac000, 0xc82000eab0)
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/lib/net.go:265 +0x105 fp=0xc820038fa0 sp=0xc820038f30
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820038fa8 sp=0xc820038fa0
created by main.(*Proxy).Initialize
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/p2p-cp/proxy.go:53 +0x428

goroutine 1 [runnable]:
main.(*Proxy).SendPing(0xc820014640)
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/p2p-cp/proxy.go:185 +0x174
main.main()
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/p2p-cp/cp.go:837 +0x1297

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 6 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/lib/go/src/runtime/time.go:59 +0xf9
main.(*Proxy).RegisterQueue(0xc820014640)
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/p2p-cp/proxy.go:204 +0x2f
created by main.(*Proxy).Initialize
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/p2p-cp/proxy.go:54 +0x44d

goroutine 7 [IO wait]:
net.runtime_pollWait(0x7efe886c83f8, 0x72, 0x0)
	/usr/lib/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820058a70, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820058a70, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readFrom(0xc820058a10, 0xc8203f9600, 0x200, 0x200, 0x0, 0x0, 0x0, 0x7efe886c3050, 0xc82000e1b0)
	/usr/lib/go/src/net/fd_unix.go:277 +0x2a5
net.(*UDPConn).ReadFromUDP(0xc82002c040, 0xc8203f9600, 0x200, 0x200, 0xc82043f358, 0x4, 0x0, 0x0)
	/usr/lib/go/src/net/udpsock_posix.go:61 +0x117
github.com/subutai-io/p2p/lib.(*DHTClient).ListenDHT(0xc820092840, 0xc82002c040, 0x0, 0x0)
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/lib/dht.go:252 +0x858
created by github.com/subutai-io/p2p/lib.(*DHTClient).Initialize
	/home/crioto/Projects/golang/src/github.com/subutai-io/p2p/lib/dht.go:490 +0xa06
```

**Comment by crioto** [comment]
Fixed in master
