### ISSUE TITLE
mac os p2p daemon restarting

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/p2p#172]
`p2p Cloud project 4.0.0-RC14-51-gcdc3711. Packet version: 5`

```
fatal error: concurrent map read and map write

goroutine 1300 [running]:
runtime.throw(0x5bbec0, 0x21)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc8202fcc98 sp=0xc8202fcc80
runtime.mapaccess2_faststr(0x3e6f80, 0xc8201d2a50, 0xc82023a6e0, 0x24, 0xc8202a03f8, 0x1)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc8202fccf8 sp=0xc8202fcc98
github.com/subutai-io/p2p/lib.(*PTPCloud).SendTo(0xc82013cd80, 0xc8203e07a2, 0x6, 0x6, 0xc8202fcf08, 0x0, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:794 +0x21c fp=0xc8202fcdc0 sp=0xc8202fccf8
github.com/subutai-io/p2p/lib.(*PTPCloud).HandleXpeerPingMessage(0xc82013cd80, 0xc8200c9b00, 0xc820238630)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:699 +0x2e2 fp=0xc8202fcf90 sp=0xc8202fcdc0
github.com/subutai-io/p2p/lib.(*PTPCloud).HandleXpeerPingMessage-fm(0xc8200c9b00, 0xc820238630)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:280 +0x34 fp=0xc8202fcfb0 sp=0xc8202fcf90
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8202fcfb8 sp=0xc8202fcfb0
created by github.com/subutai-io/p2p/lib.(*PTPCloud).HandleP2PMessage
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:581 +0x417

goroutine 1 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/time.go:59 +0xf9
main.Daemon(0x53eb60, 0x5, 0x0, 0x0, 0x0, 0x0)
	/Users/p1gmale0n/projects/ssf/p2p/main.go:386 +0xcea
main.main()
	/Users/p1gmale0n/projects/ssf/p2p/main.go:119 +0x168e

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 18 [syscall, 2 minutes]:
os/signal.signal_recv(0x6)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [IO wait, 2 minutes]:
net.runtime_pollWait(0xe41450, 0x72, 0xe00050)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820142060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820142060, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820142000, 0x0, 0xe41510, 0xc82035b560)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820122050, 0xc82002ce70, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820122050, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc82012e600, 0xe404a8, 0xc820122050, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2117 +0x129
net/http.Serve(0xe404a8, 0xc820122050, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1976 +0x8e
created by main.Daemon
	/Users/p1gmale0n/projects/ssf/p2p/main.go:370 +0xc03

goroutine 20 [select, 2 minutes, locked to thread]:
runtime.gopark(0x6229e0, 0xc820018f28, 0x545d00, 0x6, 0x18, 0x2)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820018f28, 0x0, 0x18)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820018f28)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/signal1_unix.go:279 +0x32c
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 21 [chan receive, 2 minutes]:
main.Daemon.func1(0xc820148060)
	/Users/p1gmale0n/projects/ssf/p2p/main.go:379 +0x6f
created by main.Daemon
	/Users/p1gmale0n/projects/ssf/p2p/main.go:384 +0xcd7

goroutine 11 [chan receive, 2 minutes]:
github.com/subutai-io/p2p/lib.(*PTPCloud).ReadDHTPeers(0xc82013cd80)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:853 +0x96
created by github.com/subutai-io/p2p/lib.(*PTPCloud).Run
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:395 +0x52

goroutine 8 [runnable]:
net.runtime_pollWait(0xe412d0, 0x72, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820143870, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820143870, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readFrom(0xc820143810, 0xc8201e0028, 0x1000, 0x1000, 0x0, 0x0, 0x0, 0xe00050, 0xc82000e120)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:277 +0x2a5
net.(*UDPConn).ReadFromUDP(0xc820122488, 0xc8201e0028, 0x1000, 0x1000, 0xc8201e0028, 0x1000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/udpsock_posix.go:61 +0x117
github.com/subutai-io/p2p/lib.(*PTPNet).Listen(0xc8201e0000, 0xc820208940)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/net.go:302 +0x81
created by github.com/subutai-io/p2p/lib.StartP2PInstance
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:368 +0x1a2c

goroutine 9 [syscall]:
syscall.Syscall(0x3, 0xb, 0xc820408900, 0x2710, 0x30, 0x28, 0x4bdfc0)
	/usr/local/Cellar/go/1.6.2/libexec/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0xb, 0xc820408900, 0x2710, 0x2710, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0xb, 0xc820408900, 0x2710, 0x2710, 0xc820408900, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/syscall/syscall_unix.go:161 +0x4d
os.(*File).read(0xc8200201e0, 0xc820408900, 0x2710, 0x2710, 0x42, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/os/file_unix.go:228 +0x75
os.(*File).Read(0xc8200201e0, 0xc820408900, 0x2710, 0x2710, 0x2710, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/os/file.go:95 +0x8a
github.com/subutai-io/p2p/lib.(*Interface).ReadPacket(0xc8200c9c20, 0x6220c0, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/tuntap_posix.go:24 +0x90
github.com/subutai-io/p2p/lib.(*PTPCloud).ListenInterface(0xc82013cd80)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:103 +0x93
created by github.com/subutai-io/p2p/lib.StartP2PInstance
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:370 +0x1a51

goroutine 29 [chan send (nil chan), 2 minutes]:
github.com/subutai-io/p2p/lib.(*DHTClient).HandleStop(0xc820134ea0, 0xc8202c63f0, 0x24, 0x0, 0x0, 0xc8201217a8, 0x4, 0xc8202c6390, 0x24, 0x0, ...)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/dht.go:508 +0x11d
github.com/subutai-io/p2p/lib.(*DHTClient).HandleStop-fm(0xc8202c63f0, 0x24, 0x0, 0x0, 0xc8201217a8, 0x4, 0xc8202c6390, 0x24, 0x0, 0x0, ...)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/dht.go:570 +0x3c
github.com/subutai-io/p2p/lib.(*DHTClient).ListenDHT(0xc820134ea0, 0xc820122498)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/dht.go:287 +0xd4d
created by github.com/subutai-io/p2p/lib.(*DHTClient).Initialize
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/dht.go:592 +0xa99

goroutine 10 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/time.go:59 +0xf9
github.com/subutai-io/p2p/lib.(*PTPCloud).Run(0xc82013cd80)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:427 +0x24a
created by main.(*Procedures).Run
	/Users/p1gmale0n/projects/ssf/p2p/instance.go:249 +0x9db

goroutine 12 [chan receive]:
github.com/subutai-io/p2p/lib.(*PTPCloud).ReadProxies(0xc82013cd80)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:864 +0xbb
created by github.com/subutai-io/p2p/lib.(*PTPCloud).Run
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:396 +0x77

goroutine 13 [chan receive (nil chan), 2 minutes]:
github.com/subutai-io/p2p/lib.(*PTPCloud).Run.func1(0xc82013cd80)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:402 +0xbf
created by github.com/subutai-io/p2p/lib.(*PTPCloud).Run
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:416 +0x9c

goroutine 14 [sleep, 2 minutes]:
time.Sleep(0x45d964b800)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/time.go:59 +0xf9
github.com/subutai-io/p2p/lib.(*DHTClient).UpdatePeers(0xc820134ea0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/dht.go:236 +0x45
created by github.com/subutai-io/p2p/lib.(*PTPCloud).Run
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:417 +0xc8

goroutine 582 [runnable]:
time.Sleep(0x3b9aca00)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/time.go:59 +0xf9
github.com/subutai-io/p2p/lib.(*NetworkPeer).StateConnected(0xc820249340, 0xc82013cd80, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/peer.go:163 +0x49b
github.com/subutai-io/p2p/lib.(*NetworkPeer).StateConnected-fm(0xc82013cd80, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/peer.go:47 +0x38
github.com/subutai-io/p2p/lib.(*NetworkPeer).Run(0xc820249340, 0xc82013cd80)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/peer.go:61 +0x930
created by github.com/subutai-io/p2p/lib.(*PTPCloud).UpdatePeers
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:900 +0x3df

goroutine 558 [sleep, 2 minutes]:
time.Sleep(0x45d964b800)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/time.go:59 +0xf9
github.com/subutai-io/p2p/lib.(*DHTClient).UpdatePeers(0xc82040e1a0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/dht.go:236 +0x45
created by github.com/subutai-io/p2p/lib.(*PTPCloud).Run
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:447 +0x6c4

goroutine 581 [runnable]:
time.Sleep(0x3b9aca00)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/time.go:59 +0xf9
github.com/subutai-io/p2p/lib.(*NetworkPeer).StateConnected(0xc820249260, 0xc82013cd80, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/peer.go:163 +0x49b
github.com/subutai-io/p2p/lib.(*NetworkPeer).StateConnected-fm(0xc82013cd80, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/peer.go:47 +0x38
github.com/subutai-io/p2p/lib.(*NetworkPeer).Run(0xc820249260, 0xc82013cd80)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/peer.go:61 +0x930
created by github.com/subutai-io/p2p/lib.(*PTPCloud).UpdatePeers
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/p2p.go:900 +0x3df

goroutine 568 [runnable]:
github.com/jackpal/bencode-go.collectInt(0xc820148540, 0xc820098c3a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/jackpal/bencode-go/parse.go:70 +0x112
github.com/jackpal/bencode-go.decodeInt64(0xc820148540, 0x4dfa3a, 0x0, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/jackpal/bencode-go/parse.go:76 +0x45
github.com/jackpal/bencode-go.decodeString(0xc820148540, 0x0, 0x0, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/jackpal/bencode-go/parse.go:85 +0x5d
github.com/jackpal/bencode-go.parseFromReader(0xc820148540, 0xe04728, 0xc82030d450, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/jackpal/bencode-go/parse.go:138 +0x2f7
github.com/jackpal/bencode-go.parse(0xe04700, 0xc8201b1f10, 0xe04728, 0xc82030d450, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/jackpal/bencode-go/parse.go:206 +0xbd
github.com/jackpal/bencode-go.unmarshalValue(0xe04700, 0xc8201b1f10, 0x4dfa80, 0xc8200f0b40, 0x199, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/jackpal/bencode-go/struct.go:309 +0x225
github.com/jackpal/bencode-go.Unmarshal(0xe04700, 0xc8201b1f10, 0x3c1660, 0xc8200f0b40, 0x0, 0x0)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/jackpal/bencode-go/struct.go:291 +0x261
github.com/subutai-io/p2p/lib.(*DHTClient).Extract(0xc82040e1a0, 0xc820098c00, 0x200, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/dht.go:152 +0x1a7
github.com/subutai-io/p2p/lib.(*DHTClient).ListenDHT(0xc82040e1a0, 0xc820164c70)
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/dht.go:280 +0xaab
created by github.com/subutai-io/p2p/lib.(*DHTClient).Initialize
	/Users/p1gmale0n/.goenv/Subutai-p2p/src/github.com/subutai-io/p2p/lib/dht.go:592 +0xa99

```

**Comment by crioto** [comment]
Fixed
