### ISSUE TITLE
Panic during `status` command executing

### ISSUE THREAD

**Issue by Lezh1k** [subutai-io/p2p#223]
```
[INFO] 2016/11/01 12:42:22 ID assigned. Continue
[INFO] 2016/11/01 12:42:22 Requesting IP
[INFO] 2016/11/01 12:42:22 Sending DHCP request
[INFO] 2016/11/01 12:42:23 No IP were received. Requesting again
[INFO] 2016/11/01 12:42:23 Sending DHCP request
[INFO] 2016/11/01 12:42:26 No IP were received. Requesting again
[INFO] 2016/11/01 12:42:26 Sending DHCP request
[INFO] 2016/11/01 12:42:29 No IP were received. Requesting again
[INFO] 2016/11/01 12:42:29 Sending DHCP request
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x405816]

goroutine 250 [running]:
panic(0x7a3160, 0xc4200100e0)
    /usr/lib/go/src/runtime/panic.go:500 +0x1a1
main.(*Procedures).Status(0xc420011ac8, 0xc420294510, 0xc42013cd80, 0x0, 0x0)
    /home/crioto/Projects/golang/src/github.com/subutai-io/p2p/instance.go:377 +0x156
reflect.Value.call(0xc4200622a0, 0xc42002a268, 0x13, 0x808315, 0x4, 0xc420289ef0, 0x3, 0x3, 0x5c, 0x1000, ...)
    /usr/lib/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc4200622a0, 0xc42002a268, 0x13, 0xc420289ef0, 0x3, 0x3, 0x0, 0x0, 0x800)
    /usr/lib/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420057f80, 0xc420057980, 0xc4204b7940, 0xc42009a700, 0xc42013c300, 0x770520, 0xc420294510, 0x16, 0x7704e0, 0xc42013cd80, ...)
    /usr/lib/go/src/net/rpc/server.go:383 +0x148
created by net/rpc.(*Server).ServeCodec
    /usr/lib/go/src/net/rpc/server.go:477 +0x421
```

 When we try to join to some swarm and in that moment execute `p2p status` we have this panic.

**Comment by crioto** [comment]
Fixed
