### ISSUE TITLE
panic in daemon

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#418]
```
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: [WARNING] 2017/10/30 13:57:49 Peer b73f7556-bd44-11e7-8de6-06a434709061: Peer b73f7556-bd44-11e7-8de6-06a434709061 has been timed out
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x7afe43]
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: goroutine 6809 [running]:
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: github.com/subutai-io/p2p/lib.(*PeerList).GetEndpointAndProxy(0xc420181410, 0xc420236420, 0x11, 0x0, 0x0, 0x0, 0x0)
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]:         /tmp/jenkins_slave/workspace/nap.subutai-io.pipeline_dev-FWCS3JUBEBEBS2AYY7NGBQIQYTMENZJTCGA4RZ35FZMGU242PLDQ/parts/p2p/go/src/github.com/subutai-io/p2p/lib/peerlist.go:117 +0x113
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: github.com/subutai-io/p2p/lib.(*PeerToPeer).SendTo(0xc42030ca80, 0xc420262070, 0x6, 0x64, 0xc4201a6360, 0x0, 0x0, 0xbe75d6d76f72dc90)
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]:         /tmp/jenkins_slave/workspace/nap.subutai-io.pipeline_dev-FWCS3JUBEBEBS2AYY7NGBQIQYTMENZJTCGA4RZ35FZMGU242PLDQ/parts/p2p/go/src/github.com/subutai-io/p2p/lib/p2p.go:810 +0x14e
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: github.com/subutai-io/p2p/lib.(*PeerToPeer).handlePacketIPv4(0xc42030ca80, 0xc4201d7000, 0x66, 0x1000, 0x800)
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]:         /tmp/jenkins_slave/workspace/nap.subutai-io.pipeline_dev-FWCS3JUBEBEBS2AYY7NGBQIQYTMENZJTCGA4RZ35FZMGU242PLDQ/parts/p2p/go/src/github.com/subutai-io/p2p/lib/packet.go:137 +0x1ae
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: github.com/subutai-io/p2p/lib.(*PeerToPeer).(github.com/subutai-io/p2p/lib.handlePacketIPv4)-fm(0xc4201d7000, 0x66, 0x1000, 0x800)
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]:         /tmp/jenkins_slave/workspace/nap.subutai-io.pipeline_dev-FWCS3JUBEBEBS2AYY7NGBQIQYTMENZJTCGA4RZ35FZMGU242PLDQ/parts/p2p/go/src/github.com/subutai-io/p2p/lib/p2p.go:350 +0x52
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: github.com/subutai-io/p2p/lib.(*PeerToPeer).handlePacket(0xc42030ca80, 0xc4201d7000, 0x66, 0x1000, 0x800)
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]:         /tmp/jenkins_slave/workspace/nap.subutai-io.pipeline_dev-FWCS3JUBEBEBS2AYY7NGBQIQYTMENZJTCGA4RZ35FZMGU242PLDQ/parts/p2p/go/src/github.com/subutai-io/p2p/lib/packet.go:119 +0x89
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]: created by github.com/subutai-io/p2p/lib.(*PeerToPeer).ListenInterface
Oct 30 13:57:49 mikeshost subutai-dev.p2p-service[30434]:         /tmp/jenkins_slave/workspace/nap.subutai-io.pipeline_dev-FWCS3JUBEBEBS2AYY7NGBQIQYTMENZJTCGA4RZ35FZMGU242PLDQ/parts/p2p/go/src/github.com/subutai-io/p2p/lib/p2p.go:113 +0x6f
```

**Comment by crioto** [comment]
Fixed
