### ISSUE TITLE
Client side crash

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/p2p#529]
The following happened just now on my client side p2p daemon.  Unable to reproduce but it happened while the p2p was running and environments got modified on masterhub.

```bash
[INFO] 2018/01/10 08:47:55 Interface vptp1: fe80::844c:ccff:fe6e:e1d9/64. Type: Link Local Unicast. No IPv4
[INFO] 2018/01/10 08:47:55 Interface vptp2: 10.182.39.246/24. Type: Global Unicast. Saving
[INFO] 2018/01/10 08:47:55 Interface vptp2: fe80::b4ff:b5ff:fe70:afb1/64. Type: Link Local Unicast. No IPv4
[INFO] 2018/01/10 08:47:55 4 interfaces were saved
[WARNING] 2018/01/10 08:47:55 Failed to parse TTL. Falling back to default value of 1 hour
[ERROR] 2018/01/10 08:47:55 Failed to parse provided TTL value: strconv.ParseInt: parsing "default": invalid syntax
[INFO] 2018/01/10 08:47:55 Traffic encryption is enabled. Key valid until 2018-01-10 09:47:55.034554828 +0800 +08 m=+3911.583011308
[INFO] 2018/01/10 08:47:55 Routers: 54.93.172.70:6881
[INFO] 2018/01/10 08:47:55 Started keep alive session with 54.93.172.70:6882
[INFO] 2018/01/10 08:47:55 Started UDP listener
[INFO] 2018/01/10 08:47:55 Start request
[INFO] 2018/01/10 08:47:55 Started UDP listener
[INFO] 2018/01/10 08:47:55 Proxy connection with 35.159.10.202:40622 [EP: <nil>] has died
panic: runtime error: index out of range

goroutine 54 [running]:
github.com/subutai-io/p2p/lib.(*PeerToPeer).HandlePingMessage(0xc42033e000, 0xc420316080, 0xc4200648d0)
       /home/lth/go/src/github.com/subutai-io/p2p/lib/p2p.go:763 +0x3b1
github.com/subutai-io/p2p/lib.(*PeerToPeer).HandlePingMessage-fm(0xc420316080, 0xc4200648d0)
       /home/lth/go/src/github.com/subutai-io/p2p/lib/p2p.go:418 +0x3e
github.com/subutai-io/p2p/lib.(*PeerToPeer).HandleP2PMessage(0xc42033e000, 0x13, 0xc4200648d0, 0x0, 0x0, 0xc42030d330, 0x1000, 0x1000)
       /home/lth/go/src/github.com/subutai-io/p2p/lib/p2p.go:744 +0x411
github.com/subutai-io/p2p/lib.(*PeerToPeer).HandleP2PMessage-fm(0x13, 0xc4200648d0, 0x0, 0x0, 0xc42030d330, 0x1000, 0x1000)
       /home/lth/go/src/github.com/subutai-io/p2p/lib/p2p.go:262 +0x73
github.com/subutai-io/p2p/lib.(*Network).Listen(0xc42030d300, 0xc420306500)
       /home/lth/go/src/github.com/subutai-io/p2p/lib/net.go:395 +0xdb
created by github.com/subutai-io/p2p/lib.New
       /home/lth/go/src/github.com/subutai-io/p2p/lib/p2p.go:262 +0x74c
```

**Comment by crioto** [comment]
Also happens during DHT/CP redeploy

**Comment by crioto** [comment]
Fixed
