### ISSUE TITLE
p2p crashes

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#901]
Happens under unknown circumstances. 
```
goroutine 790389 [running]:
runtime.throw(0x93952b, 0x15)
        /usr/local/go/src/runtime/panic.go:605 +0x9c fp=0xc042509e50 sp=0xc042509e30 pc=0x42d09c
runtime.mapassign_fast64(0x8a80a0, 0xc0421b2ed0, 0x6, 0xc04259c050)
        /usr/local/go/src/runtime/hashmap_fast.go:519 +0x3d9 fp=0xc042509eb0 sp=0xc042509e50 pc=0x40d029
github.com/subutai-io/p2p/lib.(*NetworkPeer).Run(0xc04255e000, 0xc042084160)
        /var/lib/jenkins/workspace/tag.builders/p2p.subutai-io.tag/.goenv/src/github.com/subutai-io/p2p/lib/peer.go:86 +0x1d9 fp=0xc042509fd0 sp=0xc042509eb0 pc=0x7bb8b9
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc042509fd8 sp=0xc042509fd0 pc=0x45a6e1
created by github.com/subutai-io/p2p/lib.(*PeerList).RunPeer
        /var/lib/jenkins/workspace/tag.builders/p2p.subutai-io.tag/.goenv/src/github.com/subutai-io/p2p/lib/peerlist.go:151 +0x29f
```

**Comment by AlinaPenkina** [comment]
Done.
