### ISSUE TITLE
p2p crashes

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#939]
```
May 10 06:16:14 subutai p2p[4022]: panic: runtime error: index out of range
May 10 06:16:14 subutai p2p[4022]: goroutine 28708 [running]:
May 10 06:16:14 subutai p2p[4022]: github.com/subutai-io/p2p/lib.(*PeerToPeer).HandleXpeerPingMessage(0xc4202a0420, 0xc42035ba20, 0xc4201d90e0)
May 10 06:16:14 subutai p2p[4022]: #011/tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/packet_handler.go:126 +0xb04
May 10 06:16:14 subutai p2p[4022]: github.com/subutai-io/p2p/lib.(*PeerToPeer).HandleXpeerPingMessage-fm(0xc42035ba20, 0xc4201d90e0)
May 10 06:16:14 subutai p2p[4022]: #011/tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/p2p.go:374 +0x3e
May 10 06:16:14 subutai p2p[4022]: github.com/subutai-io/p2p/lib.(*PeerToPeer).HandleP2PMessage(0xc4202a0420, 0x3a, 0xc4201d90e0, 0x0, 0x0, 0xc42016c630, 0x1000, 0x1000)
May 10 06:16:14 subutai p2p[4022]: #011/tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/packet_handler.go:44 +0x4a8
May 10 06:16:14 subutai p2p[4022]: github.com/subutai-io/p2p/lib.(*PeerToPeer).HandleP2PMessage-fm(0x3a, 0xc4201d90e0, 0x0, 0x0, 0xc42016c630, 0x1000, 0x1000)
May 10 06:16:14 subutai p2p[4022]: #011/tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/p2p.go:209 +0x73
May 10 06:16:14 subutai p2p[4022]: github.com/subutai-io/p2p/lib.(*Network).Listen(0xc42016c600, 0xc420052600)
May 10 06:16:14 subutai p2p[4022]: #011/tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/net.go:208 +0xd1
May 10 06:16:14 subutai p2p[4022]: created by github.com/subutai-io/p2p/lib.New
May 10 06:16:14 subutai p2p[4022]: #011/tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/p2p.go:209 +0x8f8
May 10 06:16:15 subutai systemd[1]: subutai-p2p.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 10 06:16:15 subutai systemd[1]: subutai-p2p.service: Unit entered failed state.
May 10 06:16:15 subutai systemd[1]: subutai-p2p.service: Failed with result 'exit-code'.
May 10 06:16:15 subutai systemd[1]: subutai-p2p.service: Service hold-off time over, scheduling restart.
May 10 06:16:15 subutai systemd[1]: Stopped Subutai P2P Daemon.
May 10 06:16:15 subutai systemd[1]: Started Subutai P2P Daemon.
```

**Comment by AlinaPenkina** [comment]
Done.
