### ISSUE TITLE
panic in sortEndpoints

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#981]
```
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: panic: runtime error: makeslice: len out of range
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: goroutine 435222 [running]:
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: net.hexString(0xfffff8253c894864, 0xccccccccccccc3ff, 0xfffff825048b4864, 0x0, 0x0)
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /usr/lib/go-1.10/src/net/ip.go:327 +0x43
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: net.IP.String(0xfffff8253c894864, 0xccccccccccccc3ff, 0xfffff825048b4864, 0xc420475ea0, 0xc)
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /usr/lib/go-1.10/src/net/ip.go:284 +0x374
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: net.ipEmptyString(0xfffff8253c894864, 0xccccccccccccc3ff, 0xfffff825048b4864, 0x5, 0xc4202a3f20)
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /usr/lib/go-1.10/src/net/ip.go:340 +0x56
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: net.(*UDPAddr).String(0x457760, 0xc4202a3f20, 0x12)
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /usr/lib/go-1.10/src/net/udpsock.go:35 +0x4d
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: github.com/subutai-io/p2p/lib.(*NetworkPeer).sortEndpoints(0xc4200e62c0, 0xc420412160, 0x3, 0x4, 0xc42005c180, 0x3, 0x4, 0x44a1d8, 0x40193806ca677, 0x2, ...)
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/peer.go:337 +0x25b
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: github.com/subutai-io/p2p/lib.(*NetworkPeer).route(0xc4200e62c0, 0xc420412160, 0x2, 0xc42038ae98)
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/peer.go:390 +0x74
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: github.com/subutai-io/p2p/lib.(*NetworkPeer).stateConnected(0xc4200e62c0, 0xc420412160, 0xa4ba97cb, 0x3b6d19e7d54c5151)
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/peer.go:417 +0x39
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: github.com/subutai-io/p2p/lib.(*NetworkPeer).(github.com/subutai-io/p2p/lib.stateConnected)-fm(0xc420412160, 0xc4203d6c00, 0x7)
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/peer.go:91 +0x34
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: github.com/subutai-io/p2p/lib.(*NetworkPeer).Run(0xc4200e62c0, 0xc420412160)
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/peer.go:120 +0x6a5
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]: created by github.com/subutai-io/p2p/lib.(*PeerList).RunPeer
Jun 04 04:40:51 prod-peer-us-3 p2p[7892]:         /tmp/deb_slave/workspace/tag.builders/p2p-deb.subutai-io.tag/obj-x86_64-linux-gnu/src/github.com/subutai-io/p2p/lib/peerlist.go:151 +0x28a
Jun 04 04:40:51 prod-peer-us-3 systemd[1]: subutai-p2p.service: Failed with result 'exit-code'.
```

**Comment by AlinaPenkina** [comment]
Done.
